stages:
  - build

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - export PATH=$PATH:/usr/local/bin
  - git checkout develop
  - gits populate
  
CLOSURE_Job:
  stage: build
  script: 
   - ./build.sh -n
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 21 days
    paths:
     - ci
