FROM ubuntu:20.04
MAINTAINER acichocki@perspectalabs.com
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update                                   
RUN apt-get -y install					\
    gcc							\
    make						\
    git							\
    libz3-dev						\
    libzmq3-dev						\
    libconfig-dev					\
    python3-pip						\
    wget						\
    libboost-all-dev 					\
    bc 							\
    xdot						\
    sudo



