
node {

  def closure_img = docker.image("closure_ubuntu_develop")  

  stage('Checkout Closure') {
    closure_img.inside {
      git clone "https://github.com/gaps-closure/build"
      sh 'ls -l build'
    }
  }
    
  stage('Build Closure') {
        closure_img.inside {
            sh 'ls -l build'
        }
    }
}
