name: docker

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build the Docker image
      run: docker build -f Dockerfile.dev -t closuredev:$(date +%s) . 